### ISSUE TITLE
Crashes on Win 10 when changing lightning mode

### ISSUE THREAD

**Issue by RedX2501** [subraizada3/27gn950controller#15]
I'm on windows 10 and have a 38gn950-b.

I installed HID, qt5 and the GUI opens fine.

I run it via powershell as admin with `python gui.py`
Python version 3.9.2

I downloaded the code as as a zip today.

When I click pretty much any of the button it crashes with:

```
Traceback (most recent call last):
  File "F:\Drivers\27gn950controller-master\gui.py", line 61, in <lambda>
    x.clicked.connect(lambda _, i=i: self.set_static_color(i+1))
  File "F:\Drivers\27gn950controller-master\gui.py", line 159, in set_static_color
    self.send_command(cmd)
  File "F:\Drivers\27gn950controller-master\gui.py", line 147, in send_command
    lib27gn950.send_command(cmd, devs)
  File "F:\Drivers\27gn950controller-master\lib27gn950.py", line 185, in send_command
    send_str(header + _cmd + end + padding, _dev)
  File "F:\Drivers\27gn950controller-master\lib27gn950.py", line 231, in send_str
    dev.write(i.to_bytes(65, byteorder='big'))
  File "C:\Python39\lib\site-packages\hid\__init__.py", line 155, in write
    return self.__hidcall(hidapi.hid_write, self.__dev, data, len(data))
  File "C:\Python39\lib\site-packages\hid\__init__.py", line 146, in __hidcall
    raise HIDException(err)
hid.HIDException: The I/O operation has been aborted because of either a thread exit or an application request.
```

On the LG UltraGear ControlCenter the monitor is not recognized, I get the "Please connect USB cable (...) to PC and Monitor." I don't know why I'm getting that message since I have the mouse connected to the USB-Port of the monitor and it is working fine.

What can I do to help you fix this?

**Comment by imkebe** [comment]
Was the LG UltraGear software running at that moment? It shouldn't. Maybe was in a background? That looks like somenthing was trying to access device at the same moment.

**Comment by RedX2501** [comment]
I looked today and there were no LG or UltraGear SW running (not event in the background) as far as I can tell.

![grafik](https://user-images.githubusercontent.com/929932/156887058-de1bdc4a-d09e-46cb-8e44-b243c4f1a628.png)
